### ISSUE TITLE
[JsonConverter(typeof(UtcDateTimeConverter))] may no longer be needed on Item DueDateUtc?

### ISSUE THREAD

**Issue by fluxium** [olsh/todoist-net#2]
Not sure if Todoist changed the format on due_date_utc, but I was getting DataTime conversion errors when requesting Items with a due date. I commented the JsonConverter decorator on DueDateUtc in the Item model and I could get Items with due dates without error.

Results from curl requesting an Item with due_date_utc populated:
date_added      : Sat 12 May 2018 02:50:19 +0000
due_date_utc    : Tue 12 Jun 2018 06:59:59 +0000

**Comment by olsh** [comment]
Hi @fluxium ,

Thank you for the reporting.

I've tried to reproduce the issue with the following code:
```csharp
            var dueDateUtc = DateTime.UtcNow.Date.AddDays(5);
            var item = new Item("demo task") { DueDateUtc = dueDateUtc };
            client.Items.AddAsync(item).Wait();

            var itemInfo = client.Items.GetAsync(item.Id).Result;

            Assert.True(dueDateUtc == itemInfo.Item.DueDateUtc);
```
And the test is passed.
Could you please provide steps to reproduce?

**Comment by olsh** [comment]
Hi @fluxium,

Managed to reproduce this issue. It seems like there is a bug in Newtonsoft.Json version 5.0.8, [these settings](https://github.com/olsh/todoist-net/blob/master/src/Todoist.Net/TodoistClient.cs#L27) are ignored on deserialization in this version.
Updated the dependency to 6.0.8 and set up integration tests for full framework version to spot this kind of issues.

Thank you again.
