### ISSUE TITLE
Plans for API v8?

### ISSUE THREAD

**Issue by frankhommers** [olsh/todoist-net#4]
Do you have plans to support API v8?

**Comment by olsh** [comment]
Hi @frankhommers 

Didn't hear about v8 before, thanks!

I'll update the library when [the migration guide](https://developer.todoist.com/sync/v8/#migration-guide) will be updated

**Comment by frankhommers** [comment]
I think the migration guide is complete now. However, I currently don't *need* it. The v7 in combination with your package is working perfect for me! I love it!

**Comment by olsh** [comment]
Hi @frankhommers 

Glad to hear!

Yes, the migration guide is here, but I want _to wait a little more_.
The official library [is on v7 too](https://github.com/Doist/todoist-python/pull/55) and v7 API is not deprecated yet. So, probably v8 is not stabilized yet.

**Comment by PotHix** [comment]
@olsh v8 is already stable. We will start the deprecation process of v7 soon. :)

**Comment by olsh** [comment]
Hi guys, I started to work on the migration.

@PotHix, it seems like there is a discrepancy with actual behavior and the docs.

https://developer.todoist.com/sync/v8/#get-activity-logs
The activity method returns an object, not an array.

Another undocumented change
https://developer.todoist.com/sync/v8/#add-an-item
In v8 `Add an item`  method doesn't return an error if I try to add a new task with unexisting project ID.
But in v7 it does.

**Comment by lefcha** [comment]
@olsh 
>  The activity method returns an object, not an array.

This was just fixed, thanks!

>  In v8 Add an item method doesn't return an error if I try to add a new task with unexisting project ID.

This is actually the behavior of the API endpoint when invalid data is sent to it (contrary to what is documented), and currently we don't document what happens in different API calls when invalid data are sent to them.

You're right that some functions like `item_add` may have changed the way they work between v7 and v8, and for example do a best effort (eg. add the task in the Inbox, nstead of returning an error).  I can guess that if you relied on a specific behavior, it will not work anymore and need adaptations from your side.

Still, we are considering how we can improve our documentation to be more clear on which cases errors are raised, what kind of errors, or what kind of defaults are used in some cases.

**Comment by olsh** [comment]
Version 2.0.0 was published to NuGet.
Thanks! 👍
