### ISSUE TITLE
Migrate from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by splendid25** [olsh/todoist-net#48]
Hello,

I'm trying to use this library in a .NET8 AOT app, but it seems the Newtonsoft.Json is not compatible with AOT.
Is a migration planned in the netstandard2 version of the library, to use the more recent System.Text.Json ?

I took a quick look, and there are a few uses of JsonConverter and DefaultContractResolver that can't be migrated as is.

**Comment by olsh** [comment]
Hi

> Is a migration planned in the netstandard2 version of the library, to use the more recent System.Text.Json ?

Nothing is planned at the moment, since I don't have a lot of time to work on the project. But it would be nice to migrate to System.Text.Json. PR is welcome.

**Comment by splendid25** [comment]
Awesome work, thank you !
I meant to take a shot at this, but didn't have time yet :)
