### ISSUE TITLE
Make ITodoistRestClient or public and/or make RateLimitAwareRestClient available

### ISSUE THREAD

**Issue by frankhommers** [olsh/todoist-net#5]
I would like to use the logic of the RateLimitAwareRestClient in my project.
But the ITodoistRestClient is internal, so I can't.

I would love to use it.

**Comment by olsh** [comment]
Starting from the 1.5.0 version, you can provide a custom implementation of ITodoistRestClient.

**Comment by frankhommers** [comment]
Awesome! <3
