### ISSUE TITLE
Getting today's items is not convinient

### ISSUE THREAD

**Issue by selmaohneh** [olsh/todoist-net#6]
I'd like to poll all my todos that are due today. That's one of todoist's main features.

If I've seen it right, that is not very convinient with todoist-net. I could

1. poll ALL items with `Items.GetAsync` and afterwards filter myself via `DueDate.HasValue && DueDate.Date.Date == Datetime.Now.Date`

2. Create my own custom today filter in todoist, retrieve that filter in todoist.net via `Filter.GetAsync`. But how can I only poll items with a given ItemFilter?

Wouldn't it be great to have a direct method in todoist-net? Something like Items.GetTodaysItemsAsync()?

Otherwise I'd like to have some help/info on how that use case is intended to work.

Thanks in advance!

**Comment by olsh** [comment]
Hey @selmaohneh,

Thank you for the feedback. 👍 

> Wouldn't it be great to have a direct method in todoist-net? Something like Items.GetTodaysItemsAsync()?

It seems like there is no API for getting such tasks. https://developer.todoist.com/sync/v8/
But it's pretty easy to implement an extension method for this.

> But how can I only poll items with a given ItemFilter?

Again, I'm not sure if there is an API for this. Todoist approach is [sync](https://developer.todoist.com/sync/v8/#read-resources) everything at the start and do incremental updates after the initial synchronization.

If you believe that there is an API for this, please let me know and I'll implement the methods. 
PR is appreciated too.

**Comment by olsh** [comment]
Closed due to inactivity, feel free to reopen it.
