### ISSUE TITLE
Business Admin list all Projects and Items

### ISSUE THREAD

**Issue by mar72vin** [olsh/todoist-net#8]
Is it possible to list all Projects and Items (including completed items) from all users in a Business Account?

From what I can tell the API only allows access via a single users API Token. Is there a global token that you are aware of?

**Comment by olsh** [comment]
Hi @mar72vin 

I don't have a Business account, so I know nothing about the features.
I suggest checking the docs https://developer.todoist.com/sync/v8/ probably you can find something there.

PRs are welcome. :)

**Comment by mar72vin** [comment]
Thanks Olsh. I have confirmed that there is no way to do this. The current Sync API is really only designed for a single user (not business account).
 
The biggest shortcomings are:
1) Cannot retrieve a list of all Users.
2) Cannot retrieve a list of all Projects.
3) Cannot retrieve a list of Completed Items if a Collaborator has completed them.
